import 'swiper/css'
import Head from 'next/head'

import Hero from 'components/hero'
import Brands from 'components/brands'
import PopularCourses from 'components/popular-courses'
import BookOurCourse from 'components/book-course'
import Testimonials from 'components/testimonials'
import Mentors from 'components/mentors'
import BannerNeedHelp from 'components/banner-need-help'
import Footer from 'components/footer'

export default function Home() {
  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:wght@100;200;300;400;500;600;700;800&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Hero />
      <Brands />
      <PopularCourses />
      <BookOurCourse />
      <Testimonials />
      <Mentors />
      <BannerNeedHelp />
      <Footer />
    </>
  )
}
